### ISSUE TITLE
Incompatible and thus disabled in IDEA 2021.2.1

### ISSUE THREAD

**Issue by AndriyKalashnykov** [mirkoalicastro/maven-version-refactor-plugin#19]
Plugin error: Plugin 'Maven Version Refactor' (version '1.0.2') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-212.5080.55

![idea-plugin-error](https://user-images.githubusercontent.com/2081253/132015122-ef82b6a9-a4fe-4e8b-a84c-9303762c338b.jpg)

**Comment by mirkoalicastro** [comment]
Hi @AndriyKalashnykov, I'll have a look soon. Thank you!

**Comment by mirkoalicastro** [comment]
@AndriyKalashnykov Plugin 1.0.5 is gonna fix it. JetBrains is reviewing the update. I'll keep this issue open until then.

**Comment by AndriyKalashnykov** [comment]
Awesome, thanks for prompt action!

**Comment by mirkoalicastro** [comment]
Version 1.0.5 released 🚀
All good with that version, so closing this issue! Thanks for raising it.
